-- Battery News service schema
-- Apply after the Supabase project is created. All exposed tables use RLS.

create table if not exists public.articles (
  id text primary key,
  title text not null,
  url text not null unique,
  summary text,
  region text not null default 'Global',
  application text not null default 'Etc',
  material text not null default 'Etc',
  score numeric(4,1) not null default 3,
  source text,
  lang text not null default 'ko',
  keyword text,
  published timestamptz,
  collected_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.article_celltypes (
  article_id text not null references public.articles(id) on delete cascade,
  celltype text not null,
  primary key (article_id, celltype)
);

create table if not exists public.article_hashtags (
  article_id text not null references public.articles(id) on delete cascade,
  hashtag text not null,
  primary key (article_id, hashtag)
);

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  name text not null unique,
  stage text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.article_companies (
  article_id text not null references public.articles(id) on delete cascade,
  company_id bigint not null references public.companies(id) on delete cascade,
  primary key (article_id, company_id)
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.article_feedback (
  user_id uuid not null references auth.users(id) on delete cascade,
  article_id text not null references public.articles(id) on delete cascade,
  reaction text not null check (reaction in ('like', 'dislike')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, article_id)
);

-- AI가 최초 생성한 회사별 굵직한 사건을 보관한다.
create table if not exists public.timeline_events (
  id uuid primary key default gen_random_uuid(),
  event_key text not null unique,
  company text not null,
  stage text,
  event_type text not null,
  event_date date not null,
  region text not null default 'Global',
  application text not null default 'Etc',
  material text not null default 'Etc',
  summary text not null,
  details text,
  source_articles jsonb not null default '[]'::jsonb,
  source_article_ids text[] not null default '{}',
  ai_model text,
  status text not null default 'active' check (status in ('active','superseded')),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.regional_weekly_reports (
  id uuid primary key default gen_random_uuid(),
  region text not null,
  week_start date not null,
  report jsonb not null,
  eagle_review jsonb,
  sources jsonb not null default '[]'::jsonb,
  ai_model text not null default 'gpt-5.6-luna',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (region, week_start)
);

create table if not exists public.saved_filters (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  filter jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.ai_runs (
  id bigint generated by default as identity primary key,
  run_date date not null default current_date,
  stage text not null check (stage in ('candidate_filter', 'ranking', 'rule_update')),
  model text,
  candidate_count integer not null default 0,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  status text not null default 'completed' check (status in ('running', 'completed', 'failed')),
  error_message text,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_rankings (
  id bigint generated by default as identity primary key,
  article_id text not null references public.articles(id) on delete cascade,
  ai_run_id bigint references public.ai_runs(id) on delete set null,
  ai_score numeric(5,2),
  rank integer,
  selected boolean not null default false,
  reason text,
  model text,
  prompt_version text,
  created_at timestamptz not null default now(),
  unique (article_id, ai_run_id)
);

create table if not exists public.daily_top_news (
  run_date date not null,
  article_id text not null references public.articles(id) on delete cascade,
  rank integer not null check (rank between 1 and 10),
  ai_ranking_id bigint references public.ai_rankings(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (run_date, article_id),
  unique (run_date, rank)
);

create table if not exists public.rule_versions (
  id bigint generated by default as identity primary key,
  version text not null unique,
  source text not null default 'manual' check (source in ('manual', 'feedback', 'ai')),
  status text not null default 'draft' check (status in ('draft', 'active', 'archived')),
  rules jsonb not null default '{}'::jsonb,
  change_summary text,
  created_at timestamptz not null default now(),
  activated_at timestamptz
);

create table if not exists public.rule_signals (
  id bigint generated by default as identity primary key,
  rule_version_id bigint not null references public.rule_versions(id) on delete cascade,
  signal_type text not null check (signal_type in ('keyword', 'company', 'region', 'application', 'material', 'source')),
  signal text not null,
  positive_count integer not null default 0,
  negative_count integer not null default 0,
  weight numeric(5,2) not null default 0,
  confidence numeric(5,4) not null default 0,
  created_at timestamptz not null default now(),
  unique (rule_version_id, signal_type, signal)
);

create index if not exists articles_published_idx on public.articles (published desc);
create index if not exists articles_score_idx on public.articles (score desc);
create index if not exists feedback_user_idx on public.article_feedback (user_id);
create index if not exists timeline_events_lookup_idx on public.timeline_events (company, event_date desc, event_type);
create index if not exists regional_weekly_reports_week_region_idx on public.regional_weekly_reports (week_start desc, region);
create index if not exists saved_filters_user_idx on public.saved_filters (user_id);
create index if not exists ai_rankings_article_idx on public.ai_rankings (article_id, created_at desc);
create index if not exists ai_rankings_selected_idx on public.ai_rankings (selected, created_at desc);
create index if not exists daily_top_news_date_idx on public.daily_top_news (run_date desc, rank);
create index if not exists rule_signals_lookup_idx on public.rule_signals (signal_type, signal);

alter table public.articles enable row level security;
alter table public.article_celltypes enable row level security;
alter table public.article_hashtags enable row level security;
alter table public.companies enable row level security;
alter table public.article_companies enable row level security;
alter table public.profiles enable row level security;
alter table public.article_feedback enable row level security;
alter table public.timeline_events enable row level security;
alter table public.regional_weekly_reports enable row level security;
alter table public.saved_filters enable row level security;
alter table public.ai_runs enable row level security;
alter table public.ai_rankings enable row level security;
alter table public.daily_top_news enable row level security;
alter table public.rule_versions enable row level security;
alter table public.rule_signals enable row level security;

create policy "authenticated users can read articles"
  on public.articles for select to authenticated using (true);
create policy "authenticated users can read article celltypes"
  on public.article_celltypes for select to authenticated using (true);
create policy "authenticated users can read article hashtags"
  on public.article_hashtags for select to authenticated using (true);
create policy "authenticated users can read companies"
  on public.companies for select to authenticated using (true);
create policy "authenticated users can read article companies"
  on public.article_companies for select to authenticated using (true);

create policy "users can read their profile"
  on public.profiles for select to authenticated using ((select auth.uid()) = id);
create policy "users can update their profile"
  on public.profiles for update to authenticated
  using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

create policy "users can manage their feedback"
  on public.article_feedback for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "authenticated users can read timeline events"
  on public.timeline_events for select to authenticated using (true);

create policy "users can manage their saved filters"
  on public.saved_filters for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- 선별 결과는 로그인 사용자에게만 공개한다. 수집기/AI 쓰기는 서버 작업에서 수행한다.
create policy "authenticated users can read ai rankings"
  on public.ai_rankings for select to authenticated using (true);
create policy "authenticated users can read daily top news"
  on public.daily_top_news for select to authenticated using (true);
create policy "authenticated users can read active rules"
  on public.rule_versions for select to authenticated using (status = 'active');
create policy "authenticated users can read rule signals"
  on public.rule_signals for select to authenticated using (true);

-- Data API access is deliberately explicit because automatic table exposure is disabled.
grant usage on schema public to authenticated;
grant select on public.articles, public.article_celltypes, public.article_hashtags,
  public.companies, public.article_companies, public.ai_rankings,
  public.daily_top_news, public.rule_versions, public.rule_signals to authenticated;
grant select, insert, update, delete on public.article_feedback, public.saved_filters to authenticated;
grant select on public.timeline_events to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- 권역 보고서는 서버 API만 접근한다. service_role 키는 Vercel 서버 환경변수에만 둔다.
revoke all on public.regional_weekly_reports from anon, authenticated;
grant select, insert, update, delete on public.regional_weekly_reports to service_role;
